# Schema for the configuration files of the Recipe module.

recipe.settings:
  type: config_object
  label: 'Recipe settings'
  mapping:
    total_time:
      type: mapping
      label: 'Total time'
      mapping:
        label:
          type: label
          label: 'The label for the Total time pseudo-field.'
        label_display:
          type: string
          label: 'The display setting for the Total time pseudo-field label.'
    yield:
      type: mapping
      label: 'Yield'
      mapping:
        label:
          type: label
          label: 'The label for the Yield pseudo-field.'
        label_display:
          type: string
          label: 'The display setting for the Yield pseudo-field label.'
