ingredient.settings:
  type: config_object
  label: 'Ingredient settings'
  mapping:
    ingredient_name_normalize:
      type: integer
      label: 'Normalize ingredient names to lowercase'
    ingredient_preferred_system_of_measure:
      type: integer
      label: 'Preferred system of measure'
    ingredient_preferred_system_of_measure_limit:
      type: integer
      label: 'Limit the UI to the preferred system of measure'

field.storage_settings.ingredient:
  type: mapping
  label: 'Ingredient settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.ingredient:
  type: mapping
  label: 'Ingredient settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection settings'
    default_unit:
      type: string
      label: 'The default unit to display in the ingredient widget'

field.formatter.settings.ingredient_default:
  type: mapping
  label: 'Ingredient display settings'
  mapping:
    fraction_format:
      type: string
      label: 'Fractions display string'
    unit_display:
      type: integer
      label: Ingredient unit display
    link:
      type: boolean
      label: 'Link name to the referenced ingredient'
