ingredient.settings:
  type: config_object
  label: 'Ingredient settings'
  mapping:
    ingredient_preferred_system_of_measure:
      type: integer
      label: 'Preferred system of measure'
    ingredient_preferred_system_of_measure_limit:
      type: integer
      label: 'Limit the UI to the preferred system of measure'
